QuanLySach/Controllers/HomeController.cs
using QuanLySach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace QuanLySach.Controllers
{

    public class HomeController : Controller
    {
       
        BookManagementDataContext db = new BookManagementDataContext();

        public ActionResult Index()
        {
            
                var sp = (from s in db.books
                          join c in db.book_categories on s.code_category equals c.code
                          join j in db.book_join_authors on s.id equals j.id_book
                          join a in db.authors on j.id_author equals a.id
                          where s.priority != 4 && s.status == 1
                          orderby s.id descending
                          select new ChiTietSach
                          {
                              Id = s.id,
                              tenSach = s.name,
                              gia = (float)s.price,
                              moTa = s.description,
                              tenTacGia = a.name,
                              chuDe = c.name,
                              bio = a.bio,

                          }).FirstOrDefault();
                return View(sp);
            
            
        }
        public ActionResult IndexKH()
        {
           
                var sp = (from s in db.books
                          join c in db.book_categories on s.code_category equals c.code
                          join j in db.book_join_authors on s.id equals j.id_book
                          join a in db.authors on j.id_author equals a.id
                          where s.priority != 4 && s.status == 1
                          orderby s.id descending
                          select new ChiTietSach
                          {
                              Id = s.id,
                              tenSach = s.name,
                              gia = (float)s.price,
                              moTa = s.description,
                              tenTacGia = a.name,
                              chuDe = c.name,
                              bio = a.bio,

                          }).FirstOrDefault();
                return View(sp); 
            
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Wishlist()
        {
            if (Session["id"] != null)
            {
                int userId = (int)Session["id"];
                var wishlistItems = db.wishlists
                                      .Where(w => w.id_user == userId)
                                      .Join(db.books,
                                            w => w.id_book,
                                            b => b.id,
                                            (w, b) => b) // Lấy thông tin sách từ bảng books
                                      .ToList();
                return View(wishlistItems);
            }
            else
            {
                return RedirectToAction("DangNhap", "NguoiDung");
            }
        }
        public ActionResult ComingSoon()
        {
            return View(db.books.Where(t => t.priority == 4 && t.status == 1).ToList());
        }
        
    }
}

QuanLySach/Controllers/KhachHang/WishlistController.cs
using QuanLySach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLySach.Controllers.KhachHang
{
    public class WishlistController : Controller
    {
        BookManagementDataContext db = new BookManagementDataContext();

        [HttpPost]
        public ActionResult AddToWishlist(int bookId)
        {
            // Kiểm tra người dùng đã đăng nhập hay chưa
            if (Session["id"] != null)
            {
                int userId = (int)Session["id"];

                // Kiểm tra xem sách đã tồn tại trong wishlist của người dùng chưa
                var existingItem = db.wishlists.FirstOrDefault(w => w.id_user == userId && w.id_book == bookId);
                if (existingItem == null)
                {
                    // Thêm sách vào wishlist
                    var wishlistItem = new wishlist
                    {
                        id_user = userId,
                        id_book = bookId,
                        create_date = DateTime.Now
                    };

                    db.wishlists.InsertOnSubmit(wishlistItem);
                    db.SubmitChanges();
                    return Json(new { success = true, message = "Đã thêm vào wishlist!" });
                }
                else
                {
                    return Json(new { success = false, message = "Sách đã có trong wishlist!" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Bạn cần đăng nhập để lưu vào wishlist." });
            }
        }

    }
}

QuanLySach/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;

namespace QuanLySach.Controllers
{
    public class LayoutController : Controller
    {
        BookManagementDataContext db = new BookManagementDataContext();
        public ActionResult Category()
        {
            // Use LINQ to get categories and their active products
            var categories = db.book_categories
                .Select(c => new CategoryViewModel
                {
                    name = c.name,
                    Products = db.books
                        .Where(p => p.status == 1 && p.code_category == c.code && p.priority != 4)
                        .OrderByDescending(p=>p.id)
                        .Select(p => new ProductViewModel
                        {
                            Id = p.id,
                            Name = p.name,
                            Price = p.price,
                            Quantity = p.quantity,
                        })
                        .Take(4).ToList()
                })
                .OrderByDescending(c=>c.name).Take(5).ToList();
            
            return View(categories);
        }
        // GET: Layout
        
        public ActionResult Header()
        {
            return View();
        }
        public ActionResult HeaderKH()
        {
            return View();
        }

        public ActionResult Footer()
        {
            return View();
        }

        public ActionResult Banner()
        {
            var books = db.books.Where(s=>s.priority!=4 && s.status == 1).ToList(); 
            return View(books);
        }
    }
}

QuanLySach/Views/Home/ComingSoon.cshtml
@model IEnumerable<QuanLySach.Models.book>

@{
    if (Session["id"] != null)
    {
        ViewBag.Title = "Sách sắp ra mắt";
        Layout = "~/Views/Shared/LayoutKH.cshtml";
    }
    else
    {
        ViewBag.Title = "Sách sắp ra mắt";
        Layout = "~/Views/Shared/Layout.cshtml";
    }
}
<h1 class="fw-bold mb-4" style="font-family: EB Garamond; font-size: 116px; transform: translate(76px); margin-top: 100px" align="center">SÁCH SẮP RA MẮT</h1>
<div class="container-fluid" style="padding-top: 100px">
   
    <div class="row px-xl-5 pb-3">
        @{
            foreach (var item in Model)
            {
                if (item == null) { continue; }
                @Html.Action("ComingSoon", "Sach", new { id = item.id })
            }
        }
    </div>
</div>

QuanLySach/Views/Home/Index.cshtml
@model QuanLySach.Models.ChiTietSach
@{
    ViewBag.Title = "Trang Chủ";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<!-- Banner -->
@Html.Action("Banner", "Layout")
<section class="py-5">
    <div class="container author">
        <div class="row gy-4 gy-md-0">
            <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                <div style="max-width: 350px; width: 500px;">

                    <h2 class="text-capitalize fw-bold"
                        style="
                                        font-family: Helvetica Neue;
                                        width: 351px;
                                        /*height: 139.562px;*/
                                        margin: -5px;
                                        padding: -7px;
                                        text-align: left;
                                        font-size: 50px;
                                    ">
                        <p style="color: var(--ast-global-color-2); background-color: rgb(242, 245, 247)">@Model.tenSach</p>
                    </h2>
                    <p class="my-3" style="font-family: Eb Garamond; text-align: justify">
                        @Model.moTa.Substring(0, Model.moTa.Length/3) ...
                    </p>
                    <a class="btn btn-primary btn-lg border-dark me-2"
                       role="button"
                       href="@Url.Action("ThemGioHang", "GioHang", new { @ms = Model.Id })"
                       style="font-family: Heebo; color: rgb(255, 250, 250); background: rgb(0, 0, 0)">Mua Ngay</a><a class="btn btn-outline-primary btn-lg border-dark"
                                                                                                                      role="button"
                                                                                                                      href="@Url.Action("XemChiTiet", "Sach", new { @ms = Model.Id })"
                                                                                                                      style="font-family: Heebo; color: rgb(31, 32, 34)">Chi Tiết</a>
                </div>
            </div>
            <div class="col-md-6" data-aos="fade" data-aos-delay="50">
                <div class="p-xl-5 m-xl-5">
                    <img class="rounded img-fluid w-100 fit-cover"
                         style="min-height: 300px"
                         src="@Url.Action("GetImage", "Sach", new { id = Model.Id })"
                         loading="lazy" />
                </div>
            </div>
        </div>
    </div>
    <div class="container author">
        <div class="row gy-4 gy-md-0">
            <div class="col-md-6">
                <div class="p-xl-5 m-xl-5">
                    <img class="rounded img-fluid w-100 fit-cover"
                         style="min-height: 300px"
                         src="@Url.Action("GetImageAuthor", "Sach", new { id = Model.Id })"
                         loading="lazy" />
                </div>
            </div>
            <div class="col-md-6 d-md-flex align-items-md-center" style="font-family: EB Gamunt">
                <div style="max-width: 350px">
                    <h2 class="text-uppercase fw-bold">@Model.tenTacGia</h2>
                    <p class="my-3" style="width: 447px; font-family: heebo; text-align: justify; font-size: 16px">
                        <br />@Model.bio<br />
                    </p>
                    @*<a class="btn btn-primary btn-lg border-dark me-2"
                        role="button"
                        href="#"
                        style="color: rgb(27, 23, 23); background: rgba(55, 99, 244, 0)">Đọc Thêm</a>*@
                </div>
            </div>
        </div>
    </div>
    <section></section>
    <div class="row" style="margin: 0px; margin-left: 65px; margin-right: 65px; margin-top: 0px">
        <div class="col-md-4" style="text-align: left">
            <h1 style="font-size: 27px; font-weight: bold; font-family: EB Gamunt">Giải thưởng Guiness</h1>
            <p style="font-family: heebo; font-size: 16px;">Tác giả có số lượng sách bán chạy nhất của Brazil (1991)</p>
        </div>
        <div class="col-md-4" style="text-align: center">
            <h1 style="font-size: 27px; font-weight: bold; font-family: EB Gamunt">Giải thưởng Quốc Gia&nbsp;</h1>
            <p style="font-family: heebo; font-size: 16px; ">Quốc gia văn học Italia (2001)</p>
        </div>
        <div class="col-md-4" style="text-align: right">
            <h1 style="font-weight: bold; font-size: 28px; font-family: EB Gamunt">Giải Thưởng Áo</h1>
            <p style="font-family: heebo; font-size: 16px;">Cross of Honour for Science Art (2014)</p>
        </div>
    </div>
</section>

<!--Danh mục sản phẩm-->
<div class="container-list">
    <div class="container">
        @Html.Action("FeaturedBook", "Sach")
        <section></section>
        @Html.Action("NewBook", "Sach")
        <section></section>
        @Html.Action("Category", "layout")
    </div>
</div>

QuanLySach/Views/Home/IndexKH.cshtml
@model QuanLySach.Models.ChiTietSach
@{
    ViewBag.Title = "Trang Chủ";
    Layout = "~/Views/Shared/LayoutKH.cshtml";
}

@Html.Action("Banner", "Layout")
<section class="py-5">
    <div class="container author">
        <div class="row gy-4 gy-md-0">
            <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                <div style="max-width: 350px; width: 500px;">

                    <h2 class="text-capitalize fw-bold"
                        style="
                                        font-family: Helvetica Neue;
                                        width: 351px;
                                        /*height: 139.562px;*/
                                        margin: -5px;
                                        padding: -7px;
                                        text-align: left;
                                        font-size: 50px;
                                    ">
                        <p style="color: var(--ast-global-color-2); background-color: rgb(242, 245, 247)">@Model.tenSach</p>
                    </h2>
                    <p class="my-3" style="font-family: Eb Garamond; text-align: justify">
                        @Model.moTa.Substring(0, Model.moTa.Length / 3) ...
                    </p>
                    <a class="btn btn-primary btn-lg border-dark me-2"
                       role="button"
                       href="@Url.Action("ThemGioHang", "GioHang", new { @ms = Model.Id })"
                       style="font-family: Heebo; color: rgb(255, 250, 250); background: rgb(0, 0, 0)">Mua Ngay</a><a class="btn btn-outline-primary btn-lg border-dark"
                                                                                                                      role="button"
                                                                                                                      href="@Url.Action("XemChiTiet", "Sach", new { @ms = Model.Id })"
                                                                                                                      style="font-family: Heebo; color: rgb(31, 32, 34)">Chi Tiết</a>
                </div>
            </div>
            <div class="col-md-6" data-aos="fade" data-aos-delay="50">
                <div class="p-xl-5 m-xl-5">
                    <img class="rounded img-fluid w-100 fit-cover"
                         style="min-height: 300px"
                         src="@Url.Action("GetImage", "Sach", new { id = Model.Id })"
                         loading="lazy" />
                </div>
            </div>
        </div>
    </div>
    <div class="container author">
        <div class="row gy-4 gy-md-0">
            <div class="col-md-6">
                <div class="p-xl-5 m-xl-5">
                    <img class="rounded img-fluid w-100 fit-cover"
                         style="min-height: 300px"
                         src="@Url.Action("GetImageAuthor", "Sach", new { id = Model.Id })"
                         loading="lazy" />
                </div>
            </div>
            <div class="col-md-6 d-md-flex align-items-md-center" style="font-family: EB Gamunt">
                <div style="max-width: 350px">
                    <h2 class="text-uppercase fw-bold">@Model.tenTacGia</h2>
                    <p class="my-3" style="width: 447px; font-family: heebo; text-align: justify; font-size: 16px">
                        <br />@Model.bio<br />
                    </p>
                    @*<a class="btn btn-primary btn-lg border-dark me-2"
                        role="button"
                        href="#"
                        style="color: rgb(27, 23, 23); background: rgba(55, 99, 244, 0)">Đọc Thêm</a>*@
                </div>
            </div>
        </div>
    </div>
    <section></section>
    <div class="row" style="margin: 0px; margin-left: 65px; margin-right: 65px; margin-top: 0px">
        <div class="col-md-4" style="text-align: left">
            <h1 style="font-size: 27px; font-weight: bold; font-family: EB Gamunt">Giải thưởng Guiness</h1>
            <p style="font-family: heebo; font-size: 16px;">Tác giả có số lượng sách bán chạy nhất của Brazil (1991)</p>
        </div>
        <div class="col-md-4" style="text-align: center">
            <h1 style="font-size: 27px; font-weight: bold; font-family: EB Gamunt">Giải thưởng Quốc Gia&nbsp;</h1>
            <p style="font-family: heebo; font-size: 16px; ">Quốc gia văn học Italia (2001)</p>
        </div>
        <div class="col-md-4" style="text-align: right">
            <h1 style="font-weight: bold; font-size: 28px; font-family: EB Gamunt">Giải Thưởng Áo</h1>
            <p style="font-family: heebo; font-size: 16px;">Cross of Honour for Science Art (2014)</p>
        </div>
    </div>
</section>


<!--Danh mục sản phẩm-->
<div class="container-list">
    <div class="container">
        @Html.Action("FeaturedBook", "Sach")
        <section></section>
        @Html.Action("NewBook", "Sach")
        <section></section>
        @Html.Action("Category", "layout")
    </div>
</div>

QuanLySach/Views/Home/Wishlist.cshtml
@model IEnumerable<QuanLySach.Models.book>

@{
    ViewBag.Title = "Sách Yêu Thích";
    Layout = "~/Views/Shared/LayoutKH.cshtml";
}


<h1 class="fw-bold mb-4" style="font-family: EB Garamond; font-size: 116px; transform: translate(76px); margin-top: 100px; text-align: center">SÁCH YÊU THÍCH</h1>

@if (Model != null && Model.Any())
{
    foreach (var item in Model)
    {
        <div class="col-md-3 mb-4">
            <div class="card h-40">
                <img src="@Url.Action("GetImage", "Sach", new { id = item.id })" class="card-img-top" />
                <div class="card-body">
                    <h5 class="card-title">@item.name</h5>
                    <p class="card-text"><strong>Giá:</strong> @string.Format("{0:N0}", item.price) VNĐ</p>
                    <a href="@Url.Action("ThemGioHang", "GioHang", new { @ms = item.id })" class="btn btn-dark btn-sm">Mua Ngay</a>
                    <a href="@Url.Action("XemChiTiet", "Sach", new { ms = item.id })" class="btn btn-outline-dark btn-sm">Chi Tiết</a>
                </div>
            </div>
        </div>
    }
}
else
{
    <p>Bạn chưa có sách nào trong wishlist.</p>
}